name: Markdown to PDF
on: push
jobs:
  convertToPdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: README.md
          build_html: false
      - uses: actions/upload-artifact@v4
        with:
          name: resume.pdf
          path: README.pdf
